"""Filesystem storage adapter — dev/test default (no external service).

Blocking file IO runs in a worker thread so the event loop is never blocked.
Keys are generated by the service (``<tenant_id>/<file_id>``), but the adapter
still refuses any key that would escape the configured root (defence in depth).
"""

import asyncio
from pathlib import Path
from typing import ClassVar

from core.files.ports import StorageError


class FilesystemStorage:
    backend: ClassVar[str] = "filesystem"

    def __init__(self, root: str) -> None:
        self._root = Path(root).resolve()
        self._root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        target = (self._root / key).resolve()
        if target != self._root and self._root not in target.parents:
            raise StorageError(f"storage key escapes the root: {key!r}")
        return target

    async def put(self, key: str, data: bytes, *, content_type: str) -> None:
        def _write() -> None:
            path = self._resolve(key)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

        try:
            await asyncio.to_thread(_write)
        except OSError as exc:
            raise StorageError(f"filesystem write failed: {exc}") from exc

    async def get(self, key: str) -> bytes:
        def _read() -> bytes:
            return self._resolve(key).read_bytes()

        try:
            return await asyncio.to_thread(_read)
        except OSError as exc:
            raise StorageError(f"filesystem read failed: {exc}") from exc

    async def delete(self, key: str) -> None:
        def _delete() -> None:
            self._resolve(key).unlink(missing_ok=True)  # idempotent

        try:
            await asyncio.to_thread(_delete)
        except OSError as exc:
            raise StorageError(f"filesystem delete failed: {exc}") from exc
