"""Storage port + error taxonomy for core/files (interfaces: ports/adapters).

Adapters (filesystem, s3) are structurally typed against ``StoragePort``; the
factory ``build_storage`` selects one by config. A backend failure is a
``StorageError`` (an ExternalServiceError → retried by ``call_resilient``, HTTP
502), never a silent swallow.
"""

from typing import ClassVar, Protocol

from shared.errors import ExternalServiceError


class StorageError(ExternalServiceError):
    """Object-storage backend failure (put/get/delete). Retryable; mapped to 502."""

    code = "storage_error"
    message_key = "errors.storage_error"


class StoragePort(Protocol):
    """Object store keyed by an opaque string (files uses ``<tenant_id>/<file_id>``).

    Keys are generated by the service (never user-controlled paths); adapters
    still guard against traversal. ``delete`` is idempotent (a missing key is a
    no-op) so a retried delete never errors."""

    backend: ClassVar[str]

    async def put(self, key: str, data: bytes, *, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...


class ThumbnailPort(Protocol):
    """Image-transform port: produce a resized, metadata-stripped raster variant.

    Given the source bytes, ``generate`` returns ``(bytes, content_type)`` for a
    thumbnail whose longest edge is at most ``max_edge`` (aspect ratio preserved,
    never enlarged). The output stays within the raster allowlist. CPU-bound work
    runs off the event loop. A source that cannot be decoded is a bad upload
    (``InvariantViolationError``, HTTP 422), not a backend failure."""

    backend: ClassVar[str]

    async def generate(self, data: bytes, *, max_edge: int) -> tuple[bytes, str]: ...
